default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gympass
  password: gympass

development:
  <<: *default
  database: gympass-toy-app_development

test:
  <<: *default
  database: gympass-toy-app_test

production:
  url: <%= ENV['DATABASE_URL'] %>
